import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Route5",
  description: "Route5 Terms of Service",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By accessing or using the Route5 platform, website, or any associated services (collectively, the "Services"), you agree to be bound by these Terms of Service ("Terms"). If you are using the Services on behalf of an organization, you represent that you have the authority to bind that organization to these Terms.

If you do not agree to these Terms, you may not access or use the Services.`,
  },
  {
    title: "2. Description of Services",
    content: `Route5 provides an AI-native enablement platform that analyzes legacy enterprise software systems, captures execution traces, and generates AI-consumable interfaces including APIs, SDKs, microservices, and MCP (Model Context Protocol) servers.

The Services are designed for enterprise customers with technical teams capable of evaluating and deploying generated code artifacts in controlled test environments. Route5 is not a consumer product.`,
  },
  {
    title: "3. Enterprise License",
    content: `Subject to your compliance with these Terms and payment of applicable fees, Route5 grants you a limited, non-exclusive, non-transferable, revocable license to:

- Access and use the Route5 platform for your internal business purposes.
- Deploy Route5 agents in your test and staging environments.
- Use, modify, and incorporate generated code artifacts (APIs, SDKs, wrappers, MCP servers) into your own systems and products.

You may not: sublicense, sell, resell, or transfer the Route5 platform itself; reverse engineer the Route5 platform's core AI analysis engine; or use the Services to build a competing product.`,
  },
  {
    title: "4. Customer Data and Intellectual Property",
    content: `**Your Data**: You retain all rights to your source code, execution traces, database schemas, and any other data you connect to or upload to Route5 ("Customer Data"). Route5 processes Customer Data solely to provide the Services.

**Generated Artifacts**: All code, APIs, tests, documentation, and other artifacts generated by Route5 using your Customer Data are owned by you. Route5 claims no ownership over generated artifacts.

**Route5 Technology**: Route5 retains all rights to its platform, algorithms, models, and underlying technology. Nothing in these Terms transfers ownership of Route5's technology to you.

**Feedback**: If you provide feedback, suggestions, or ideas about the Services, Route5 may use this feedback without obligation to you.`,
  },
  {
    title: "5. Acceptable Use",
    content: `You agree not to use the Services to:

- Analyze systems you do not have legal authorization to access.
- Generate capabilities that circumvent security controls or authorization systems without proper approval.
- Interfere with or disrupt the integrity or performance of the Services.
- Attempt to gain unauthorized access to any Route5 systems or networks.
- Use the Services in violation of any applicable law or regulation.
- Introduce malicious code, viruses, or harmful data into Route5 systems.

Route5 reserves the right to suspend or terminate access for violations of this section without prior notice.`,
  },
  {
    title: "6. Deployment and Production Use",
    content: `Route5 is a development and enablement tool. While Route5 provides parity validation and test generation capabilities, you are solely responsible for:

- Reviewing and approving all generated code artifacts before deployment.
- Testing generated capabilities in your own environments prior to production use.
- Ensuring generated capabilities meet your organization's security, compliance, and quality standards.
- Any consequences arising from deployment of Route5-generated artifacts in production systems.

Route5's parity validation is a best-effort comparison tool and does not guarantee that generated capabilities will be free of defects or meet all business requirements. Human review and approval is required before production deployment.`,
  },
  {
    title: "7. Fees and Payment",
    content: `Route5 is offered under subscription agreements negotiated directly with enterprise customers. Pricing, payment terms, and usage limits are specified in your Order Form or Master Service Agreement (MSA).

Unless otherwise specified in an Order Form:
- Subscription fees are due annually in advance.
- All fees are non-refundable except as required by law.
- Route5 may adjust pricing upon 90 days' written notice prior to renewal.
- Late payments accrue interest at 1.5% per month or the maximum rate permitted by law.`,
  },
  {
    title: "8. Confidentiality",
    content: `Each party agrees to protect the other's Confidential Information using at least the same degree of care used to protect its own confidential information, but not less than reasonable care.

"Confidential Information" includes all non-public information disclosed by one party to the other that is designated as confidential or that reasonably should be understood to be confidential.

Confidential Information does not include information that: (a) becomes publicly available without breach of this agreement; (b) was rightfully known before disclosure; (c) is rightfully received from a third party without restriction; or (d) is independently developed without use of the disclosing party's Confidential Information.`,
  },
  {
    title: "9. Disclaimer of Warranties",
    content: `THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.

ROUTE5 DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS, OR THAT THE GENERATED ARTIFACTS WILL MEET YOUR REQUIREMENTS OR BE SUITABLE FOR PRODUCTION DEPLOYMENT WITHOUT INDEPENDENT REVIEW AND TESTING.`,
  },
  {
    title: "10. Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ROUTE5 SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR YOUR USE OF THE SERVICES.

IN NO EVENT SHALL ROUTE5'S AGGREGATE LIABILITY EXCEED THE AMOUNT PAID BY YOU TO ROUTE5 IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.

THESE LIMITATIONS APPLY REGARDLESS OF THE THEORY OF LIABILITY AND EVEN IF ROUTE5 HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.`,
  },
  {
    title: "11. Indemnification",
    content: `You agree to indemnify, defend, and hold harmless Route5 and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable legal fees, arising out of:

- Your use of the Services in violation of these Terms.
- Your deployment of Route5-generated artifacts in production systems.
- Your breach of any representation or warranty in these Terms.
- Any claim that your Customer Data infringes the rights of a third party.`,
  },
  {
    title: "12. Term and Termination",
    content: `These Terms remain in effect for the duration of your subscription. Either party may terminate for material breach if the breach is not cured within 30 days of written notice.

Route5 may immediately suspend or terminate access if you violate the Acceptable Use policy (Section 5), fail to pay fees, or if continued operation poses a security risk.

Upon termination, your license to use the Services immediately ceases. You may export Customer Data and generated artifacts within 30 days of termination, after which Route5 may delete them.`,
  },
  {
    title: "13. Governing Law and Disputes",
    content: `These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles.

Any dispute arising under these Terms shall be resolved by binding arbitration administered by JAMS under its Commercial Arbitration Rules, with proceedings held in New York, New York. The arbitrator's decision shall be final and may be entered as a judgment in any court of competent jurisdiction.

Notwithstanding the above, either party may seek injunctive or equitable relief in a court of competent jurisdiction to protect intellectual property rights or confidential information.`,
  },
  {
    title: "14. Changes to Terms",
    content: `Route5 may update these Terms at any time. For existing customers, material changes will be communicated with at least 30 days' advance notice by email or through the platform. Continued use of the Services after the effective date constitutes acceptance of the updated Terms.

For new users, the Terms in effect at the time of account creation apply immediately.`,
  },
  {
    title: "15. Contact",
    content: `Questions about these Terms should be directed to:

**Route5, Inc.**
legal@route5.ai

For enterprise MSA inquiries: enterprise@route5.ai`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <nav className="border-b border-border">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center gap-4">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="relative w-7 h-7 flex items-center justify-center">
              <div className="absolute inset-0 bg-blue-500/20 rounded-md rotate-45" />
              <span className="relative text-blue-400 font-bold text-sm font-mono">
                R5
              </span>
            </div>
            <span className="text-lg font-semibold">
              Route<span className="text-blue-400">5</span>
            </span>
          </Link>
          <span className="text-text-secondary text-sm">/</span>
          <span className="text-sm text-text-secondary">Terms of Service</span>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16 lg:py-24">
        <div className="mb-12">
          <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
          <p className="text-text-secondary">
            Effective date: March 18, 2026 · Last updated: March 18, 2026
          </p>
        </div>

        <div className="space-y-10">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className="text-xl font-semibold mb-4">{section.title}</h2>
              <div className="text-text-secondary leading-relaxed space-y-3">
                {section.content.split("\n\n").map((para, i) => (
                  <p key={i}>{para}</p>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 pt-8 border-t border-border">
          <Link
            href="/"
            className="text-sm text-accent hover:text-blue-300 transition-colors"
          >
            ← Back to Route5.ai
          </Link>
        </div>
      </div>
    </div>
  );
}
